ssh: disable failed authentication penalty
The penalty is now enabled by default, causing tests for failed
authentication randomly fail with:

```
FAILED tests/test_access_control_simple.py::test_access_control_simple__deny_group_supersedes_allow_group (ldap) - sssd_test_framework.misc.errors.ExpectScriptError: Unexpected end of file
FAILED tests/test_authentication.py::test_authentication__user_login[root-ssh] (ldap) - sssd_test_framework.misc.errors.ExpectScriptError: Unexpected end of file
```