actions: retry start of containers upon failure
There is a race condition in podman that was fixed in v4 which is
not yet available in current ubuntu github runners.

```
ERROR: for client  Cannot start service client: error configuring network namespace for container 8d66f2cf911f87e75a2f54759808c68be3ef13088d427af04ecfe4392f025180: error adding pod client_client to CNI network "sssd-ci": running [/usr
```

This change should mitigate that.